# docker-compose.yml

version: '3.9'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
    command: celery -A app.celery_worker worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - BROKER_URL=redis://redis:6379/0

  app:
    build:
      context: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  