# docker-compose.yml

version: '3.9'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
    command: celery -A app.celery_worker worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - BROKER_URL=redis://redis:6379/0